version: '3.8'
services:
  redis:
    image: redis
    container_name: redisserver
    ports:
      - "6379:6379"

  springboot:
    image: springboot-image
    container_name: springboot
    ports:
      - "8080:8080"
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - redis

  nginx:
    image: nginx
    container_name: nginxserver
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - springboot
