package com.elice.nbbang.domain.payment.entity.enums;

public enum PaymentStatus {
    COMPLETED,
    CREATED,
    APPROVED,
    FAILED,
    CANCELED,
    SUBSCRIBED,
    PARTIAL_SETTLEMENT_COMPLETED,
    SETTLE_COMPLETED,
    REFUND_REQUESTED,
    REFUNDED_COMPLETED,
    REFUND_FAILED,
    REFUND_CANCELLED,
    RESERVE_COMPLETED,
    RESERVE_FAILED,
    RESERVE_CANCELLED
}
